- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --enable-ssl-passthrough
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --tcp-services-configmap=ingress-nginx/tcp-services
