- op: replace
  path: /spec/type
  value: LoadBalancer
- op: add
  path: /spec/ports 
  value:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: https
